apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: proxy-configured-policy
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: proxy-configured-policy
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: None
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data: '{{hub copyConfigMapData "acm-policies" (printf "custom-ca-%s" .ManagedClusterName) hub}}'
                kind: ConfigMap
                metadata:
                  name: custom-ca
                  namespace: openshift-config
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: Proxy
                metadata:
                  name: cluster
                spec:
                  trustedCA:
                    name: "custom-ca"
