apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: monitoring-configured-policy
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: monitoring-configured-policy
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: cluster-monitoring-config
                  namespace: openshift-monitoring
                data:
                  config.yaml: |
                    prometheusOperator:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoExecute
                    prometheusK8s:
                      retention: CHANGE_ME
                      volumeClaimTemplate:
                        spec:
                          storageClassName: CHANGE_ME
                          resources:
                            requests:
                              storage: 100Gi
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoExecute
                    alertmanagerMain:
                      volumeClaimTemplate:
                        spec:
                          storageClassName: CHANGE_ME
                          resources:
                            requests:
                              storage: 10Gi
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoExecute
                    kubeStateMetrics:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoExecute
                    openshiftStateMetrics:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoExecute
                    telemeterClient:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoExecute
                    k8sPrometheusAdapter:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoExecute
                    thanosQuerier:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoExecute
          pruneObjectBehavior: None
