apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: image-sources-policy
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: image-sources-policy
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: None
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: Image
                metadata:
                  name: cluster
                spec:
                  registrySources:
                    allowedRegistries:
                      - central-quay-registry.apps.infra.sandbox3104.opentlc.com
                      - image-registry.openshift-image-registry.svc:5000
                      - registry.redhat.io
                      - registry.access.redhat.com
                      - quay.io
                    insecureRegistries:
                      - central-quay-registry.apps.infra.sandbox3104.opentlc.com