apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: self-provision-allowed-policy
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: self-provision-allowed-policy
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: local-self-provisioners
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: self-provisioner
                subjects:
                - apiGroup: rbac.authorization.k8s.io
                  kind: User
                  name: user1
          pruneObjectBehavior: None
