apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: "ACM Cluster Policies"
    argocd.argoproj.io/sync-wave: "0"
  name: acm-policies
