apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: "Red Hat Advanced Cluster Manager"
    argocd.argoproj.io/sync-wave: "0"
  name: open-cluster-management
