apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: user-monitoring-configured-policy
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: user-monitoring-configured-policy
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ConfigMap
                metadata:
                  name: user-workload-monitoring-config
                  namespace: openshift-user-workload-monitoring
                data:
                  config.yaml: |
                    prometheusOperator:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoExecute
                    prometheus:
                      retention: CHANGE_ME
                      volumeClaimTemplate:
                        spec:
                          storageClassName: CHANGE_ME
                          resources:
                            requests:
                              storage: 100Gi
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoExecute
                    alertmanager:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoExecute
                    thanosRuler:
                      volumeClaimTemplate:
                        spec:
                          storageClassName: CHANGE_ME
                          resources:
                            requests:
                              storage: 10Gi
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kuberenetes.io/infra
                        value: reserved
                        effect: NoExecute
          pruneObjectBehavior: None
