apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: allow-ingress-default-namespace-policy
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: allow-ingress-default-namespace-policy
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  labels:
                    kubernetes.io/metadata.name: default
                    #network.openshift.io/policy-group: ingress
                  name: default
          pruneObjectBehavior: None