apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: quay-operator-installed-policy
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quay-operator-installed-policy
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: None
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: quay-operator
                  namespace: openshift-operators
                spec:
                  channel: stable-3.8
                  installPlanApproval: Automatic
                  name: quay-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace