apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: sync-operator-installed-policy
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: sync-operator-installed-policy
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: group-sync-operator
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  name: group-sync-operator
                  namespace: group-sync-operator
                spec:
                  targetNamespaces:
                    - group-sync-operator
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  name: group-sync-operator
                  namespace: group-sync-operator
                spec:
                  name: group-sync-operator
                  channel: alpha
                  installPlanApproval: Automatic
                  source: community-operators
                  sourceNamespace: openshift-marketplace
          pruneObjectBehavior: None