apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: loki-logging-instance-configured-policy
  namespace: acm-policies
spec:
  dependencies:
  - apiVersion: policy.open-cluster-management.io/v1
    compliance: Compliant
    kind: Policy
    name: loki-operator-installed-policy
    namespace: acm-policies
  - apiVersion: policy.open-cluster-management.io/v1
    compliance: Compliant
    kind: Policy
    name: logging-operator-installed-policy
    namespace: acm-policies
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: loki-logging-instance-configured-policy
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: objectbucket.io/v1alpha1
                kind: ObjectBucketClaim
                metadata:
                  name: loki-logging-obc
                  namespace: openshift-logging
                spec:
                  additionalConfig:
                    bucketclass: noobaa-default-bucket-class
                  generateBucketName: loki-logging-obc
                  storageClassName: openshift-storage.noobaa.io
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data:
                  access_key_id: '{{ fromSecret "openshift-logging" "loki-logging-obc" "AWS_ACCESS_KEY_ID" }}'
                  access_key_secret: '{{ fromSecret "openshift-logging" "loki-logging-obc" "AWS_SECRET_ACCESS_KEY" }}'
                  bucketnames: '{{ fromConfigMap "openshift-logging" "loki-logging-obc" "BUCKET_NAME" | base64enc}}'
                  endpoint: '{{ printf "https://%s:%s" (fromConfigMap "openshift-logging" "loki-logging-obc" "BUCKET_HOST") (fromConfigMap "openshift-logging" "loki-logging-obc" "BUCKET_PORT") | base64enc }}'
                kind: Secret
                metadata:
                  name: logging-loki-odf
                  namespace: openshift-logging
                type: Opaque
            - complianceType: musthave
              objectDefinition:
                apiVersion: loki.grafana.com/v1
                kind: LokiStack
                metadata:
                  name: logging-loki
                  namespace: openshift-logging
                spec:
                  size: 1x.extra-small	
                  storage:
                    secret:
                      name: logging-loki-odf
                      type: s3
                    tls:
                      caName: openshift-service-ca.crt
                  storageClassName: CHANGE_ME
                  tenants:
                    mode: openshift-logging
                  template:
                    compactor:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoExecute
                    distributor:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoExecute
                    gateway:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoExecute
                    indexGateway:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoExecute
                    ingester:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoExecute
                    querier:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoExecute
                    queryFrontend:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoExecute
                    ruler:
                      nodeSelector:
                        node-role.kubernetes.io/infra: ""
                      tolerations:
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoSchedule
                      - key: node-role.kubernetes.io/infra
                        value: reserved
                        effect: NoExecute
