apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: api-configured-policy
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: api-configured-policy
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                data:
                  tls.crt: '{{hub fromSecret "acm-policies" (printf "custom-api-certificate-%s" .ManagedClusterName) "tls.crt" hub}}'
                  tls.key: '{{hub fromSecret "acm-policies" (printf "custom-api-certificate-%s" .ManagedClusterName) "tls.key" hub}}'
                kind: Secret
                metadata:
                  name: custom-api-certificate
                  namespace: openshift-config
                type: kubernetes.io/tls
            - complianceType: musthave
              objectDefinition:
                apiVersion: config.openshift.io/v1
                kind: APIServer
                metadata:
                  name: cluster
                spec:
                  servingCerts:
                    namedCertificates:
                    - names:
                      - "api.<cluster-name>.<domain>"
                      servingCertificate:
                        name: "custom-api-certificate"
          pruneObjectBehavior: None
