apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: quay-instance-configured-policy
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: quay-instance-configured-policy
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: None
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: registry
                  annotations:
                    openshift.io/node-selector: 'node-role.kubernetes.io/infra='
                    scheduler.alpha.kubernetes.io/defaultTolerations: >-
                      [{"effect": "NoSchedule", "key": "node-role.kubernetes.io/infra", "value": "reserved"},{"effect": "NoExecute", "key": "node-role.kubernetes.io/infra", "value": "reserved"}]
            - complianceType: musthave
              objectDefinition:
                kind: QuayRegistry
                apiVersion: quay.redhat.com/v1
                metadata:
                  name: central
                  namespace: registry
                spec:
                  configBundleSecret: config-bundle-secret
                  components:
                  - kind: clair
                    managed: true
                  - kind: postgres
                    managed: true
                  - kind: objectstorage
                    managed: false
                  - kind: redis
                    managed: true
                  - kind: horizontalpodautoscaler
                    managed: true
                  - kind: route
                    managed: true
                  - kind: mirror
                    managed: true
                  - kind: monitoring
                    managed: true
                  - kind: tls
                    managed: true
                  - kind: quay
                    managed: true
                  - kind: clairpostgres
                    managed: true
