apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: etcd-backup-configured-policy
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: etcd-backup-configured-policy
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: ocp-backup-etcd
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: ServiceAccount
                metadata:
                  name: openshift-backup
                  namespace: ocp-backup-etcd
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRole
                metadata:
                  name: cluster-etcd-backup
                rules:
                - apiGroups: [""]
                  resources:
                  - "nodes"
                  verbs: ["get", "list"]
                - apiGroups: [""]
                  resources:
                  - "pods"
                  - "pods/log"
                  - "pods/attach"
                  verbs: ["get", "list", "create", "delete", "watch"]
                - apiGroups: [""]
                  resources:
                  - "namespaces"
                  verbs: ["get", "list", "create"]
            - complianceType: musthave
              objectDefinition:
                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1
                metadata:
                  name: openshift-backup
                subjects:
                - kind: ServiceAccount
                  name: openshift-backup
                  namespace: ocp-backup-etcd
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: cluster-etcd-backup
            - complianceType: musthave
              objectDefinition:
                apiVersion: rbac.authorization.k8s.io/v1
                kind: ClusterRoleBinding
                metadata:
                  name: system:openshift:scc:privileged
                roleRef:
                  apiGroup: rbac.authorization.k8s.io
                  kind: ClusterRole
                  name: system:openshift:scc:privileged
                subjects:
                - kind: ServiceAccount
                  name: openshift-backup
                  namespace: ocp-backup-etcd
            - complianceType: musthave
              objectDefinition:
                kind: CronJob
                apiVersion: batch/v1
                metadata:
                  name: openshift-backup
                  namespace: ocp-backup-etcd
                  labels:
                    app: openshift-backup
                spec:
                  schedule: "0 0 * * *"
                  concurrencyPolicy: Forbid
                  successfulJobsHistoryLimit: 5
                  failedJobsHistoryLimit: 5
                  jobTemplate:
                    metadata:
                      labels:
                        app: openshift-backup
                    spec:
                      backoffLimit: 0
                      template:
                        metadata:
                          labels:
                            app: openshift-backup
                        spec:
                          containers:
                          - name: backup
                            image: "registry.redhat.io/openshift4/ose-cli"
                            command:
                            - "/bin/bash"
                            - "-c"
                            - oc get no -l node-role.kubernetes.io/master --no-headers -o name | xargs -I {} --  oc debug {} -- bash -c 'chroot /host sudo -E /usr/local/bin/cluster-backup.sh /home/core/backup/ && chroot /host sudo -E find /home/core/backup/ -type f -ctime +"2" -delete'
                          restartPolicy: "Never"
                          terminationGracePeriodSeconds: 30
                          activeDeadlineSeconds: 600
                          dnsPolicy: "ClusterFirst"
                          serviceAccountName: "openshift-backup"
                          serviceAccount: "openshift-backup"
          pruneObjectBehavior: None
