apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: kubernetes-nmstate-operator-installed-policy 
  namespace: acm-policies
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: kubernetes-nmstate-operator-installed-policy
        spec:
          remediationAction: enforce
          severity: high
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Namespace
                metadata:
                  name: openshift-nmstate
                  labels:
                    kubernetes.io/metadata.name: openshift-nmstate
                    name: openshift-nmstate
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1
                kind: OperatorGroup
                metadata:
                  annotations:
                    olm.providedAPIs: NMState.v1.nmstate.io
                  name: openshift-nmstate
                  namespace: openshift-nmstate
                spec:
                  targetNamespaces:
                  - openshift-nmstate
            - complianceType: musthave
              objectDefinition:
                apiVersion: operators.coreos.com/v1alpha1
                kind: Subscription
                metadata:
                  labels:
                    operators.coreos.com/kubernetes-nmstate-operator.openshift-nmstate: ""
                  name: kubernetes-nmstate-operator
                  namespace: openshift-nmstate
                spec:
                  channel: stable
                  installPlanApproval: Automatic
                  name: kubernetes-nmstate-operator
                  source: redhat-operators
                  sourceNamespace: openshift-marketplace
            - complianceType: musthave
              objectDefinition:
                apiVersion: nmstate.io/v1
                kind: NMState
                metadata:
                  name: nmstate
