apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: acm-policies
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: thanos-obserbavility-storage
      endpoint: s3.us-east-2.amazonaws.com
      insecure: false
      access_key: AKIAS6PPFI6KPFZSGS4O
      secret_key: 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